import { StaffUser } from "../types";

export const MOCK_STAFF_USERS: StaffUser[] = [
  {
    id: "staff-001",
    staffId: "ADM-9021",
    name: "Dr. Marcus Vance",
    email: "marcus.vance@cityhospital.org",
    role: "HOSPITAL_ADMIN",
    hospitalId: "hosp-001",
    hospitalName: "Metropolitan Central Hospital",
    departmentName: "Hospital Administration",
    avatarUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80",
    phone: "+1 (555) 019-2834",
    permissions: [
      "APPOINTMENT_VIEW",
      "APPOINTMENT_MANAGE",
      "QUEUE_VIEW",
      "QUEUE_MANAGE",
      "DOCTOR_VIEW",
      "DOCTOR_MANAGE",
      "PATIENT_VIEW",
      "HOSPITAL_MANAGE",
      "ANALYTICS_VIEW",
      "NAVIGATION_MANAGE",
      "JOURNEY_CONFIG",
    ],
  },
  {
    id: "staff-002",
    staffId: "DOC-4102",
    name: "Dr. Sarah Mitchell, MD",
    email: "sarah.mitchell@cityhospital.org",
    role: "DOCTOR",
    hospitalId: "hosp-001",
    hospitalName: "Metropolitan Central Hospital",
    departmentId: "dept-cardiology",
    departmentName: "Cardiology",
    doctorId: "doc-cardio-1",
    avatarUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80",
    phone: "+1 (555) 014-9921",
    permissions: [
      "APPOINTMENT_VIEW",
      "QUEUE_VIEW",
      "QUEUE_MANAGE",
      "PATIENT_VIEW",
      "DOCTOR_VIEW",
    ],
  },
  {
    id: "staff-003",
    staffId: "DOC-5829",
    name: "Dr. Elena Rostova, MD",
    email: "elena.rostova@cityhospital.org",
    role: "DOCTOR",
    hospitalId: "hosp-001",
    hospitalName: "Metropolitan Central Hospital",
    departmentId: "dept-neurology",
    departmentName: "Neurology",
    doctorId: "doc-neuro-1",
    avatarUrl: "https://images.unsplash.com/photo-1594824813590-789252062635?w=150&auto=format&fit=crop&q=80",
    phone: "+1 (555) 012-7711",
    permissions: [
      "APPOINTMENT_VIEW",
      "QUEUE_VIEW",
      "QUEUE_MANAGE",
      "PATIENT_VIEW",
      "DOCTOR_VIEW",
    ],
  },
  {
    id: "staff-004",
    staffId: "REC-1044",
    name: "James Miller",
    email: "james.miller@cityhospital.org",
    role: "RECEPTION_STAFF",
    hospitalId: "hosp-001",
    hospitalName: "Metropolitan Central Hospital",
    departmentName: "Central Reception & Check-In",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    phone: "+1 (555) 018-4432",
    permissions: [
      "APPOINTMENT_VIEW",
      "APPOINTMENT_MANAGE",
      "QUEUE_VIEW",
      "QUEUE_MANAGE",
      "PATIENT_VIEW",
    ],
  },
  {
    id: "staff-005",
    staffId: "QUE-3091",
    name: "David Wong",
    email: "david.wong@cityhospital.org",
    role: "QUEUE_OPERATOR",
    hospitalId: "hosp-001",
    hospitalName: "Metropolitan Central Hospital",
    departmentId: "dept-cardiology",
    departmentName: "Cardiology Station",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    phone: "+1 (555) 016-8843",
    permissions: [
      "QUEUE_VIEW",
      "QUEUE_MANAGE",
      "APPOINTMENT_VIEW",
      "PATIENT_VIEW",
    ],
  },
];
